# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  matrix:
  - DJANGO='Django>=1.8,<1.9' NOSE_COVER_PACKAGE="djangocms_conditional" NOSE_WITH_COVERAGE=1
  - DJANGO='Django>=1.9,<1.10' NOSE_COVER_PACKAGE="djangocms_conditional" NOSE_WITH_COVERAGE=1
  - DJANGO='Django>=1.10,<1.11' NOSE_COVER_PACKAGE="djangocms_conditional" NOSE_WITH_COVERAGE=1
  - DJANGO='Django>=1.11,<1.12' NOSE_COVER_PACKAGE="djangocms_conditional" NOSE_WITH_COVERAGE=1

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - pip install -r requirements-test.txt

# command to run tests, e.g. python setup.py test
script: djangocms-helper djangocms_conditional test --cms --nose-runner

after_success: coveralls

matrix:
#  exclude:
#    - python: 2.6
#      env: DJANGO='django>=1.7,<1.8' NOSE_COVER_PACKAGE="djangocms_conditional" NOSE_WITH_COVERAGE=1
#
#  allow_failures:
#    - python: 2.7
#      env: DJANGO='django>=1.7,<1.8' NOSE_COVER_PACKAGE="djangocms_conditional" NOSE_WITH_COVERAGE=1
#    - python: 3.3
#      env: DJANGO='django>=1.7,<1.8' NOSE_COVER_PACKAGE="djangocms_conditional" NOSE_WITH_COVERAGE=1
#    - python: 3.4
#      env: DJANGO='django>=1.7,<1.8' NOSE_COVER_PACKAGE="djangocms_conditional" NOSE_WITH_COVERAGE=1