# Generated by Django 4.2.11 on 2024-04-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cms", "0022_auto_20180620_1551"),
        ("djangocms_conditional", "0002_conditionalpluginmodel_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditionalpluginmodel",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="conditionalpluginmodel",
            name="mode",
            field=models.CharField(
                choices=[
                    ("in_group", "Users in group"),
                    ("not_in_group", "Users not in group"),
                    (
                        "not_in_group_plus_anon",
                        "Anonymous users and users not in group",
                    ),
                    ("anonymous", "Anonymous users"),
                ],
                default="in_group",
                help_text="Conditional access type",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="conditionalpluginmodel",
            name="permitted_group",
            field=models.ForeignKey(
                null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to="auth.group"
            ),
        ),
    ]
